apiVersion: v1
kind: Service
metadata:
  name: grafana-external
  namespace: sre-challenge
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: grafana
  ports:
    - port: 3000
      targetPort: 3000
