apiVersion: v1
kind: Service
metadata:
  name: prometheus-external
  namespace: sre-challenge
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: prometheus
  ports:
    - port: 9090
      targetPort: 9090
