apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-api-service-monitor
  namespace: sre-challenge
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: node-api
  endpoints:
    - interval: 30s
      targetPort: 8080
      path: /metrics