apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: sre-challenge
  labels:
      app: node-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: node-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80