apiVersion: v1
kind: Service
metadata:
  name: node-api-service
  namespace: sre-challenge
  labels:
    app: node-api
spec:
  selector:
    app: node-api
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
