apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-api-deployment
  namespace: sre-challenge
  labels:
      app: node-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-api
  template:
    metadata:
      labels:
        app: node-api
    spec:
      containers:
        - name: node-api
          image: node-api:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          env:
            - name: NODE_API_PORT
              value: "8080"
            - name: REDIS_HOST
              value: "my-redis-master"
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: my-redis
                  key: redis-password